-- SQL schema for incomes table
CREATE TABLE IF NOT EXISTS incomes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  source VARCHAR(255) NOT NULL,
  amount DECIMAL(20,2) NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  category VARCHAR(100) DEFAULT 'salary',
  description TEXT,
  is_recurring TINYINT(1) DEFAULT 0,
  recurring_frequency VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (user_id),
  INDEX (date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
