// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase is disabled - using backend API instead
// Set dummy values to prevent connection errors
const SUPABASE_URL = 'https://dummy.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'dummy-key';

// Create a dummy client that won't make requests
export const supabase = {
  from: () => ({
    select: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
    insert: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
    update: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
    delete: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
  }),
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    signUp: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
    signInWithPassword: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
    signOut: async () => ({ error: null }),
    updateUser: async () => ({ data: null, error: new Error('Supabase disabled - use backend API') }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  },
} as any;
